name: slashWild
main: slashWild\Wild
version: 1.0dev
api: [3.0.0-ALPHA3]
load: STARTUP
author: eDroid and RTGNetworkkk
description: slashWild, a new and improved way to be teleported somewhere wild

commands:
 wild:
  aliases: [tprandom]
  description: teleport somewhere random and wild!
  permission: slashWild.command.wild

permissions:
  slashWild.command.wild:
    default: true
    description: /wild main permission
